add_newline = false

[username]
style_user = '#e4e3d5'
style_root = '#830000'
format = ' [$user]($style) '
disabled = false
show_always = true



[line_break]
disabled = true

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[â¨¯](bold red)'

[c]
format = ' @ [$name $version]($style)'
style = '#005494'

[container]
format = '[@ ğŸ“¦ \[$name\] ]($style)'
style = '#4067b2'

[dotnet]
format = '[ @ $symbol$version ]($style)'
style = '#4d29c9'

[rust]
format = '@ [âš™ï¸  $version](#ea4800)'

